### ISSUE TITLE
catalog-rebuild in the ZMI is broken with Python 3.8

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#3027]
`time.clock` has been replaced with `time.perf_counter`

```
2020-01-27 13:23:29,446 ERROR   [Zope.SiteErrorLog:17][waitress] 1580127809.4455750.2654625040991838 http://localhost:8080/Plone/portal_catalog/manage_catalogRebuild
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 156, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 338, in publish_module
  Module ZPublisher.WSGIPublisher, line 248, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module Products.PDBDebugMode.wsgi_runcall, line 60, in pdb_runcall
  Module Products.CMFPlone.CatalogTool, line 517, in manage_catalogRebuild
AttributeError: module 'time' has no attribute 'clock'
```

Workaround: The underlying code `clearFindAndRebuild` still works fine.

**Comment by mauritsvanrees** [comment]
On Python 2.7 I get this `DeprecationWarning`: "time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead".

I don't know which of the two would be better.
See https://docs.python.org/3/library/time.html?highlight=time#time.perf_counter and below

**Comment by pbauer** [comment]
Same as https://github.com/zopefoundation/Products.ZCatalog/issues/96 which was fixed in https://github.com/zopefoundation/Products.ZCatalog/pull/97

In `Products.PluginIndexes` is another occurence of `time.clock()`

**Comment by pbauer** [comment]
Fixed
