### ISSUE TITLE
configuration registry bug: some fields are no longer editable ttw

### ISSUE THREAD

**Issue by spereverde** [plone/Products.CMFPlone#3693]
### What I did

Create new Plone Site
Go to the configurationregistries control panel.
looked for the favicon setting and tried to edit and save

### What I expect to happen:

To be able to update and save configuration settings ttw

### What actually happened:
the popup allows no save action, nor a close action
only way to get out i pressing escape, but then the value is not saved

### What version of Plone/ Addons I am using:
Plone 6.0.0rc1 (6009)

### notes
not tested in newer version of plone, will try
not tested on many configuration settings, will try to find out which (types of) fields work and which don't

**Comment by spereverde** [comment]
```log
...
<link rel=preload> must have a valid `as` value
jquery.js:10135          
POST http://localhost:8080/Plone/portal_registry/edit/plone.site_favicon 500 (Internal Server Error)
send @ jquery.js:10135
ajax @ jquery.js:9716
(anonymous) @ jquery.form.min.js:22
e.fn.ajaxSubmit @ jquery.form.min.js:22
handleFormAction @ modal.js:233
(anonymous) @ modal.js:164
dispatch @ jquery.js:5430
g.handle @ jquery.js:5234
trigger @ jquery.js:8745
(anonymous) @ jquery.js:8823
each @ jquery.js:385
each @ jquery.js:207
trigger @ jquery.js:8822
(anonymous) @ modal.js:467
dispatch @ jquery.js:5430
g.handle @ jquery.js:5234
modal.js:250 error happened error  do something
modal.js:250 error happened timeout  do something

```

**Comment by spereverde** [comment]
also broken on Plone 6.0.0b3 (6008)

**Comment by spereverde** [comment]
seems to still work in Plone 6.0.0a6 (6005), it's a bit slow, I get a loading spinner for a long time after I click save, but then the modal closes itself and the value is saved

**Comment by petschki** [comment]
Also the ajax pagination is broken. I'm debugging the new registry implementation in mockup right now.

**Comment by petschki** [comment]
Changing bytes fields directly in `portal_registry` like `site_logo` and `site_favicon` can seriously crash the whole site. Since the widgets are only text inputs in the modal, you have to enter the valid coverted value defined in `plone.formwidget.namedfile.converter` like:
```
filenameb64:<base64 encoded filename>;datab64:<base64 encoded data>
```
if you enter it exactly like this it works.

The reason the widgets arent rendered is because the record edit traverser of `plone.app.registry` has no info about it from the `ISiteSchema` schema. in the site controlpanel it's defined via the `updateFields` method setting the `widgetFactory` property of those fields. Complex outcome ...

**Comment by spereverde** [comment]
Thanks for looking into this @petschki 
Does that mean there is no real solution for this?

**Comment by mauritsvanrees** [comment]
I wonder if my bug is a different one. What happens for me, when I look at the network tab:

- I go to the portal_registry.
- I filter on toolbar.
- I click to edit `toolbar.position`, which is a choice field.
- This opens a modal, which shows up just fine.
- I change the value and click Save.
- The network tab shows a POST to http://localhost:8080/Plone/portal_registry/edit/plone.toolbar_position.
- The answer is a 302, sending me to portal_registry.
- Nothing happens, maybe because the current url is already portal_registry.
- Most importantly, the modal stays open.
- Four more requests happen, all to `http://localhost:8080/Plone/portal_registry?q=toolbar&qp=&_authenticator=...`
- When I reload the page, the toolbar has switched to the chosen position, so the Save button did work.

**Comment by petschki** [comment]
I could look into this and refactored a few bits of `pat-registry` to fix the editing modal and the multiple XHR initializations. See https://github.com/plone/mockup/pull/1257 ... these are "quickfixes" for the UI but there's room for improvement in the `plone.app.registry` templates to use more patterns like `pat-modal` and `pat-inject` instead of handwiring the UI with `pat-registry` ... maybe someone of you can confirm.

**Comment by jensens** [comment]
Closing as outdated (3 years old). The UI-level modal/pagination bugs were fixed in mockup PR #1257. The remaining concern (Bytes fields needing special encoding) is by-design behavior of the low-level registry editor.
If you think this issue is still relevant please reopen it. Thank you for the original report!
