### ISSUE TITLE
Error when previewing a diazo theme in py3

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2962]
Error when previewing a diazo theme in Plone 5.2. Broken in Python 3.7, work in Python 2.7.

```
[14] > /home/vagrant/buildout-cache/eggs/Products.PDBDebugMode-2.0-py3.7.egg/Products/PDBDebugMode/errorlog.py(23)raising()
-> del SiteErrorLog.LOG.error
c
(Pdb++) 2019-10-21 09:13:20,329 ERROR   [waitress:38][waitress] Exception while serving /Plone/++theme++barceloneta/@@theming-controlpanel-mapper-getframe
Traceback (most recent call last):
  File "/home/vagrant/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/ZPublisher/WSGIPublisher.py", line 155, in transaction_pubevents
    yield
  File "/home/vagrant/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/ZPublisher/WSGIPublisher.py", line 337, in publish_module
    response = _publish(request, new_mod_info)
  File "/home/vagrant/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/ZPublisher/WSGIPublisher.py", line 255, in publish
    bind=1)
  File "/home/vagrant/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/ZPublisher/mapply.py", line 85, in mapply
    return debug(object, args, context)
  File "/home/vagrant/buildout-cache/eggs/Products.PDBDebugMode-2.0-py3.7.egg/Products/PDBDebugMode/wsgi_runcall.py", line 60, in pdb_runcall
    return obj(*args)
  File "/home/vagrant/buildout-cache/eggs/plone.app.theming-4.0.1-py3.7.egg/plone/app/theming/browser/mapper.py", line 269, in getFrame
    context = findContext(portal.restrictedTraverse(path))
  File "/home/vagrant/buildout-cache/eggs/plone.app.theming-4.0.1-py3.7.egg/plone/app/theming/utils.py", line 192, in findContext
    for parent in request.PARENTS:
AttributeError: 'RequestContainer' object has no attribute 'PARENTS'
```
